service: stats-aws-lambda
#TEST
provider:
  name: aws
  runtime: java8
  region: us-east-1
  timeout: 20
  memorySize: 1000
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::${self:custom.myBucket}/*'
        - !Join [ '', [ 'arn:aws:s3:::', !Ref ServerlessDeploymentBucket, '/*' ] ]
  environment:
    MAIN_CLASS: com.mercadolibre.mutantverifier.MutantVerifierApplication

custom:
  myBucket: stats-aws-lambda-bucket

package:
  artifact: target/statslambda.jar

functions:
  mutantHttp:
    handler: com.mercadolibre.mutantverifier.aws.StatsLambda
    environment:
    events:
      - http:
          path: /stats
          method: GET